2023-04-23 11:41:23,488 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2023-04-23 11:41:57,592 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2023-04-23 11:48:28,591 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-30 10:20:23,567 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-30 10:26:25,060 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2023-04-30 11:45:47,517 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-30 11:47:18,130 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-07 12:05:33,053 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-07 12:25:15,391 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-07 12:26:32,285 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 09:36:29,861 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 09:36:41,179 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:14:08,769 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:14:41,964 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:15:26,618 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:17:57,601 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:18:33,967 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:22:43,326 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:22:58,007 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:23:29,204 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:23:48,016 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:24:52,493 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:47:27,801 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:50:25,154 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:53:06,687 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:58:24,875 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 10:58:50,645 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2023-05-14 10:59:40,974 ERROR: Exception on /edit_profile [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\blog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\blog\app\route.py", line 93, in edit_profile
    return redirect(url_for('edit profile'))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit profile'. Did you mean 'edit_profile' instead?
2023-05-14 11:02:59,089 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:07:27,631 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:10:27,313 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:11:14,529 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:12:43,445 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:14:43,680 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:16:11,040 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:17:53,709 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:20:51,537 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:21:57,513 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:22:52,639 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:23:18,846 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:23:42,027 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:24:10,757 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:25:16,776 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:25:55,892 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:26:42,556 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:27:33,643 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:27:59,066 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:28:51,804 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:31:18,663 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:31:38,949 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:33:02,119 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-05-14 11:34:12,356 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
