2023-04-09 12:12:28,591 ERROR: Exception on /edit_profile [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\blog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\blog\app\route.py", line 93, in edit_profile
    return redirect(url_for('edit profile'))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit profile'. Did you mean 'edit_profile' instead?
2023-04-09 12:12:41,957 ERROR: Exception on /edit_profile [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\blog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\blog\app\route.py", line 93, in edit_profile
    return redirect(url_for('edit profile'))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit profile'. Did you mean 'edit_profile' instead?
2023-04-09 12:14:23,602 ERROR: Exception on /edit_profile [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\blog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\blog\app\route.py", line 93, in edit_profile
    return redirect(url_for('edit profile'))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit profile'. Did you mean 'edit_profile' instead?
2023-04-09 12:14:32,672 ERROR: Exception on /edit_profile [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\blog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\blog\app\route.py", line 93, in edit_profile
    return redirect(url_for('edit profile'))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit profile'. Did you mean 'edit_profile' instead?
2023-04-23 10:04:38,490 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 10:36:58,500 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 10:43:39,944 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 10:53:37,303 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 10:54:20,496 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 10:59:26,123 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:01:41,102 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:05:31,859 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:06:56,448 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:15:44,051 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:16:09,860 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/'. Did you mean 'edit_profile' instead?
2023-04-23 11:18:11,069 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:18:53,751 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2023-04-23 11:23:08,398 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:24:09,496 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:26:31,351 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:28:02,547 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:29:47,794 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:34:24,435 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:38:45,712 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
2023-04-23 11:40:06,580 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
