2023-04-23 11:41:23,488 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2023-04-23 11:41:57,592 ERROR: Exception on /login [POST] [in d:\blog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\blog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\blog\app\route.py", line 44, in login
    return redirect(url_for(next_page))
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\blog\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "d:\blog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2023-04-23 11:48:28,591 INFO: Blog startUP! [in D:\blog\app\__init__.py:27]
